### ISSUE TITLE
evaluate shape-prior

### ISSUE THREAD

**Issue by Liuchongpei** [OasisYang/Wild6D#1]
@OasisYang  Hi, thanks for your great work! I used the evaluation code to evaluate shape-prior on Wild6D and got the separate results of 5 categories. I average 5 categories' results to get the final result. However, it seems much better than that in the paper. I don't know if I did something wrong.

**Comment by OasisYang** [comment]
Hi @Liuchongpei, did you directly evaluate the shape-prior pretrained model on Wild6D testing data? In that case, you should  obtain the per-category results similar to the following table,

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/17880031/221146192-7c377317-4049-40fd-be6a-cd63191f46dd.png">

You could obtain slightly different results since the testing set is further cleaned.

**Comment by Liuchongpei** [comment]
Yes, I used the pretrained model trained on CAMERA+REAL.
![SPD_on_Wild6D](https://user-images.githubusercontent.com/34116796/221177899-f47bacd9-d5ee-4d8f-8615-efb8239a1ed1.png)
The above is what we got. The Mug and Camera are similar to yours. But others are much better. And it prints 'Not found the ground truth from ...' when evaluating the Mug and Laptop.

**Comment by OasisYang** [comment]
Sorry, I don't know what happened here. How did you obtain the shape-prior results? We follow their official codes to generate the estimation results and only evaluate them on Wild6D with our evaluation script by setting the `--only_eval` to True. In addition, did you visualize your results? Here is a visualization result, you could compare it with yours.
<img width="625" alt="image" src="https://user-images.githubusercontent.com/17880031/221299393-cda60ef1-2291-434d-8bff-9623db328902.png">

**Comment by Liuchongpei** [comment]
We only make some modifications on 'evaluate_wild6d.py'.
![改动0](https://user-images.githubusercontent.com/34116796/221460741-ca2c9e38-9dbf-431f-abd1-5ec37a9f1659.png)
![改动1](https://user-images.githubusercontent.com/34116796/221460758-8e3b53d3-a20d-49f8-9d0d-1aedbc6a27bf.png)
![改动2](https://user-images.githubusercontent.com/34116796/221460773-45b1d9fc-75e7-4b3f-a133-aecc040eb15a.png)
Here is our visualization result.
![results_bottle_0001_1_0000](https://user-images.githubusercontent.com/34116796/221461154-c331a74a-9028-4ec0-9bef-60c4d4435f22.jpg)

**Comment by OasisYang** [comment]
@Liuchongpei  Could you just extract the poses with the official Shape-prior repo and evaluate with our evaluation script to see if you can obtain similar results? 

I'm not sure what causes this difference. I guess the mean shapes used in Shape-prior are different with ours. We select the shape templates from ShapeNet dataset, while Shape-prior estimates the mean shape via a pretrained autoencoder.

**Comment by Liuchongpei** [comment]
Ok,I will have a try later. Did you evaluate NOCS on Wild6D?
